spring.application.name=delivery_food

spring.datasource.url=jdbc:postgresql://localhost:5432/mini_delivery_food_db
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}

spring.jpa.show-sql=true
# bunu ekleyince otomatik tablo oluşturabilir
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.orm.jdbc.bind=TRACE

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

jwt.secret=test-jwt-secret-for-unit-tests-only-256bit-minimum-length-required123456789
jwt.expiration=3600000
